# Generated by Django 4.1.2 on 2023-01-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Animals'},
        ),
    ]
