# Generated by Django 4.1.2 on 2023-01-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_animal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='likes_cat',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=3),
        ),
        migrations.AlterField(
            model_name='animal',
            name='likes_kids',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], max_length=3),
        ),
    ]
