# Generated by Django 4.1.2 on 2023-01-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_animal_likes_cat_alter_animal_likes_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='likes_cat',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='animal',
            name='likes_kids',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='no', max_length=3),
        ),
    ]
