# Generated by Django 4.1.2 on 2023-01-06 13:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_animal_ani_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='likes_cat',
            new_name='likes_cats',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_class',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_image',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='ani_type',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='name',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_age',
            field=models.IntegerField(default=34, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_class',
            field=models.CharField(choices=[('Small', 'small'), ('Medium', 'medium'), ('Large', 'large')], default='small', max_length=10),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(default='asset_img/default.jpg', null=True, upload_to=app.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='activity_level',
            field=models.CharField(choices=[('Small', 'small'), ('Medium', 'medium'), ('Large', 'large')], default='small', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='bio',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('Small', 'small'), ('Medium', 'medium'), ('Large', 'large')], default='small', max_length=10),
        ),
    ]
