# Generated by Django 4.1.2 on 2023-01-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_likes_cat_animal_likes_cats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='bio',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
