# Generated by Django 4.1.2 on 2023-01-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_animal_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='likes_dogs',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='animal',
            name='activity_level',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('High', 'High')], default='small', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_class',
            field=models.CharField(choices=[('Young', 'Young'), ('Adult', 'Adult'), ('Senior', 'Senior')], default='small', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='small', max_length=10),
        ),
    ]
